---
- name: Create responder configure stack
  cloudformation:
    aws_access_key: "{{ cloud_vpn_responder_aws_access_key  }}"
    aws_secret_key: "{{ cloud_vpn_responder_aws_secret_key  }}"
    security_token: "{{ cloud_vpn_responder_aws_security_token | default(omit) }}"
    region: "{{ cloud_vpn_responder_aws_region }}"
    stack_name: "{{ cloud_vpn_name }}-responder-configure-stack"
    template_body: "{{ lookup('template', 'templates/providers/aws_vpn/responder/configure_bgp.j2') }}"

- name: Get VPC facts
  ec2_vpc_vpn_facts:
    aws_access_key: "{{ cloud_vpn_responder_aws_access_key }}"
    aws_secret_key: "{{ cloud_vpn_responder_aws_secret_key }}"
    security_token: "{{ cloud_vpn_responder_aws_security_token | default(omit) }}"
    region: "{{ cloud_vpn_responder_aws_region }}"
    filters:
      tag:Name: "{{ cloud_vpn_name }}-responder-vpn"
  register: out

- name: Set responder IP fact
  set_fact:
    cloud_vpn_responder_public_ip: "{{ out['vpn_connections'][0]['vgw_telemetry'][0]['outside_ip_address'] }}"

- name: Set responder failover IP fact
  set_fact:
    cloud_vpn_responder_failover_ip: "{{ out['vpn_connections'][0]['vgw_telemetry'][1]['outside_ip_address'] }}"

- name: Set customer gateway configuration fact
  set_fact:
    out_cgw_configuration: "{{ out['vpn_connections'][0]['customer_gateway_configuration'] | regex_replace('\n', '') }}"

- name: Get tunnel ip addresses from customer gateway
  xml:
    xmlstring: "{{ out_cgw_configuration }}"
    xpath: /vpn_connection/ipsec_tunnel/customer_gateway/tunnel_inside_address/ip_address
    content: text
  register: out

- name: Set initiator tunnel IP
  set_fact:
    cloud_vpn_initiator_tunnel_ip: "{{ out['matches'][0]['ip_address'] }}"

- name: Set initiator tunnel failover IP
  set_fact:
    cloud_vpn_initiator_tunnel_failover_ip: "{{ out['matches'][1]['ip_address'] }}"

- name: Get tunnel ip addresses from vpn gateway
  xml:
    xmlstring: "{{ out_cgw_configuration }}"
    xpath: /vpn_connection/ipsec_tunnel/vpn_gateway/tunnel_inside_address/ip_address
    content: text
  register: out

- name: Set responder tunnel IP
  set_fact:
    cloud_vpn_responder_tunnel_ip: "{{ out['matches'][0]['ip_address'] }}"

- name: Set responder tunnel failover IP
  set_fact:
    cloud_vpn_responder_tunnel_failover_ip: "{{ out['matches'][1]['ip_address'] }}"

- name: Get BGP ASN from vpn gateway
  xml:
    xmlstring: "{{ out_cgw_configuration }}"
    xpath: /vpn_connection/ipsec_tunnel/vpn_gateway/bgp/asn
    content: text
  register: out

- name: Set responder BGP ASN fact
  set_fact:
    cloud_vpn_responder_bgp_asn: "{{ out['matches'][0]['asn'] }}"
