---

- name: Include provider get default tasks
  include_tasks: "get_{{ cloud_vpn_initiator_type }}_defaults.yaml"

- name: Create initiator cloudformation stack
  cloudformation:
    aws_access_key: "{{ cloud_vpn_initiator_aws_access_key  }}"
    aws_secret_key: "{{ cloud_vpn_initiator_aws_secret_key  }}"
    security_token: "{{ cloud_vpn_initiator_aws_security_token | default(omit) }}"
    region: "{{ cloud_vpn_initiator_aws_region }}"
    stack_name: "{{ cloud_vpn_name }}-initiator-stack"
    template_body: "{{ lookup('template', 'templates/aws_instance/initiator/provision.j2') }}"

- name: Get initiator instance facts
  ec2_instance_facts:
    aws_access_key: "{{ cloud_vpn_initiator_aws_access_key }}"
    aws_secret_key: "{{ cloud_vpn_initiator_aws_secret_key }}"
    security_token: "{{ cloud_vpn_initiator_aws_security_token | default(omit) }}"
    region: "{{ cloud_vpn_initiator_aws_region }}"
    filters:
      tag:Name: "{{ cloud_vpn_name }}-initiator-instance"
      instance-state-name: running
  register: out

- name: Set initiator IP fact
  set_fact:
    cloud_vpn_initiator_ip: "{{ out['instances'][0]['public_ip_address'] }}"
