---
- name: Include provider get default tasks
  include_tasks: "get_{{ cloud_vpn_initiator_type }}_defaults.yaml"

- name: Set Azure image publisher fact
  set_fact:
    cloud_vpn_initiator_azure_image_publisher: "{{ cloud_vpn_initiator_image_id.split(':')[0] }}"

- name: Set Azure image offer fact
  set_fact:
    cloud_vpn_initiator_azure_image_offer: "{{ cloud_vpn_initiator_image_id.split(':')[1] }}"

- name: Set Azure image SKU fact
  set_fact:
    cloud_vpn_initiator_azure_image_sku: "{{ cloud_vpn_initiator_image_id.split(':')[2] }}"

- name: Set Azure image version fact
  set_fact:
    cloud_vpn_initiator_azure_image_version: "{{ cloud_vpn_initiator_image_id.split(':')[3] }}"

- name: Create initiator resource group
  azure_rm_resourcegroup:
    name: "{{ cloud_vpn_name }}-initiator-resource-group"
    location: "{{ cloud_vpn_initiator_azure_region }}"
    subscription_id: "{{ cloud_vpn_initiator_azure_subscription_id }}"
    tenant: "{{ cloud_vpn_initiator_azure_tenant }}"
    client_id: "{{ cloud_vpn_initiator_azure_client_id }}"
    secret: "{{ cloud_vpn_initiator_azure_secret }}"

- name: Create Azure initiator stack
  azure_rm_deployment:
    resource_group: "{{ cloud_vpn_name }}-initiator-resource-group"
    deployment_name: "{{ cloud_vpn_name }}-initiator-template"
    template: "{{ lookup('template', 'templates/azure_instance/initiator/provision.j2') }}"
    subscription_id: "{{ cloud_vpn_initiator_azure_subscription_id }}"
    tenant: "{{ cloud_vpn_initiator_azure_tenant }}"
    client_id: "{{ cloud_vpn_initiator_azure_client_id }}"
    secret: "{{ cloud_vpn_initiator_azure_secret }}"
  register: out

- name: Set initiator IP fact
  set_fact:
    cloud_vpn_initiator_ip: "{{ out['deployment']['instances'][0]['ips'][0]['public_ip'] }}"
