---

- name: Include provision responder tasks if needed
  include_tasks: provision_responder.yaml
  when: cloud_vpn_responder_provisioner_role is defined

- name: Include provision initiator tasks if needed
  include_tasks: provision_initiator.yaml
  when: cloud_vpn_initiator_provisioner_role is defined

- name: Load responder provider defaults
  include_tasks: load_responder_defaults.yaml

- name: Load initiator provider defaults
  include_tasks: load_initiator_defaults.yaml

- name: Include add host responder tasks
  include_tasks: add_host_responder.yaml

- name: Include add host initiator tasks
  include_tasks: add_host_initiator.yaml

- name: Include configure vpn responder tasks
  include_tasks: configure_vpn_responder.yaml

- name: Include configure vpn initiator tasks
  include_tasks: configure_vpn_initiator.yaml

- name: Include configure routing responder tasks
  include_tasks: configure_routing_responder.yaml

- name: Include configure routing initiator tasks
  include_tasks: configure_routing_initiator.yaml

- name: Include post configure initiator hooks tasks
  include_tasks: post_configure_initiator_hooks.yaml

- name: Include post configure responder hooks tasks
  include_tasks: post_configure_responder_hooks.yaml

- name: Include show login info responder tasks
  include_tasks: show_login_info_responder.yaml

- name: Include show login info initiator tasks
  include_tasks: show_login_info_initiator.yaml
