---

- name: Include responder role show login info tasks
  include_role:
    name: "{{ cloud_vpn_responder_provider_role }}"
    tasks_from: "{{ cloud_vpn_responder_provider }}/responder/show_login_info"
