---
- name: Delete initiator cloudformation stack
  cloudformation:
    aws_access_key: "{{ cloud_vpn_initiator_aws_access_key  }}"
    aws_secret_key: "{{ cloud_vpn_initiator_aws_secret_key  }}"
    security_token: "{{ cloud_vpn_initiator_aws_security_token | default(omit) }}"
    region: "{{ cloud_vpn_initiator_aws_region }}"
    stack_name: "{{ cloud_vpn_name }}-initiator-stack"
    state: absent
