---

- name: Include provider get default tasks
  include_tasks: "get_{{ cloud_vpn_responder_provider }}_defaults.yaml"

- name: Create responder cloudformation stack
  cloudformation:
    aws_access_key: "{{ cloud_vpn_responder_aws_access_key  }}"
    aws_secret_key: "{{ cloud_vpn_responder_aws_secret_key  }}"
    security_token: "{{ cloud_vpn_responder_aws_security_token | default(omit) }}"
    region: "{{ cloud_vpn_responder_aws_region }}"
    stack_name: "{{ cloud_vpn_name }}-responder-stack"
    template_body: "{{ lookup('template', 'templates/provisioners/aws_instance/responder/provision.j2') }}"

- name: Get responder instance facts
  ec2_instance_facts:
    aws_access_key: "{{ cloud_vpn_responder_aws_access_key }}"
    aws_secret_key: "{{ cloud_vpn_responder_aws_secret_key }}"
    security_token: "{{ cloud_vpn_responder_aws_security_token | default(omit) }}"
    region: "{{ cloud_vpn_responder_aws_region }}"
    filters:
      tag:Name: "{{ cloud_vpn_name }}-responder-instance"
      instance-state-name: running
  register: out

- name: Set responder IP fact
  set_fact:
    cloud_vpn_responder_public_ip: "{{ out['instances'][0]['public_ip_address'] }}"
