---
- ec2_vpc_net_facts:
    aws_access_key: "{{ cloud_vpn_aws_access_key }}"
    aws_secret_key: "{{ cloud_vpn_aws_secret_key }}"
    region: "{{ cloud_vpn_aws_region }}"
    filters:
      tag:Name: "{{ cloud_vpn_name }}-responder-vpc"
  register: out

- set_fact:
    cloud_vpn_responder_vpc_id: "{{ out['vpcs'][0]['vpc_id'] }}"

- ec2_vpc_route_table_facts:
    aws_access_key: "{{ cloud_vpn_aws_access_key }}"
    aws_secret_key: "{{ cloud_vpn_aws_secret_key }}"
    region: "{{ cloud_vpn_aws_region }}"
    filters:
      vpc-id: "{{ cloud_vpn_responder_vpc_id }}"
  register: out

- set_fact:
    cloud_vpn_responder_route_table_id: "{{ out['route_tables'][0]['id'] }}"

- cloudformation:
    aws_access_key: "{{ cloud_vpn_aws_access_key  }}"
    aws_secret_key: "{{ cloud_vpn_aws_secret_key  }}"
    region: "{{ cloud_vpn_aws_region }}"
    stack_name: "{{ cloud_vpn_name }}-responder-configure-stack"
    template_body: "{{ lookup('template', 'templates/aws_vpn/responder/configure.j2') }}"

- ec2_vpc_vpn_facts:
    aws_access_key: "{{ cloud_vpn_aws_access_key }}"
    aws_secret_key: "{{ cloud_vpn_aws_secret_key }}"
    region: "{{ cloud_vpn_aws_region }}"
    filters:
      tag:Name: "{{ cloud_vpn_name }}-responder-vpn"
  register: out

- set_fact:
    cloud_vpn_responder_ip: "{{ out['vpn_connections'][0]['vgw_telemetry'][0]['outside_ip_address'] }}"

- set_fact:
    cloud_vpn_responder_failover_ip: "{{ out['vpn_connections'][0]['vgw_telemetry'][1]['outside_ip_address'] }}"

- set_fact:
    out_cgw_configuration: "{{ out['vpn_connections'][0]['customer_gateway_configuration'] | regex_replace('\n', '') }}"

- xml:
    xmlstring: "{{ out_cgw_configuration }}"
    xpath: /vpn_connection/ipsec_tunnel/customer_gateway/tunnel_inside_address/ip_address
    content: text
  register: out

- set_fact:
    cloud_vpn_initiator_tunnel_a_ip: "{{ out['matches'][0]['ip_address'] }}"

- set_fact:
    cloud_vpn_initiator_tunnel_b_ip: "{{ out['matches'][1]['ip_address'] }}"

- xml:
    xmlstring: "{{ out_cgw_configuration }}"
    xpath: /vpn_connection/ipsec_tunnel/vpn_gateway/tunnel_inside_address/ip_address
    content: text
  register: out

- set_fact:
    cloud_vpn_responder_tunnel_a_ip: "{{ out['matches'][0]['ip_address'] }}"

- set_fact:
    cloud_vpn_responder_tunnel_b_ip: "{{ out['matches'][1]['ip_address'] }}"
