---
- cloudformation:
    aws_access_key: "{{ cloud_vpn_responder_aws_access_key  }}"
    aws_secret_key: "{{ cloud_vpn_responder_aws_secret_key  }}"
    security_token: "{{ cloud_vpn_responder_aws_security_token }} | default(omit)"
    region: "{{ cloud_vpn_responder_aws_region }}"
    stack_name: "{{ cloud_vpn_name }}-responder-provision-stack"
    template_body: "{{ lookup('template', 'templates/aws_vpn/responder/provision.j2') }}"

- ec2_vpc_net_facts:
    aws_access_key: "{{ cloud_vpn_responder_aws_access_key }}"
    aws_secret_key: "{{ cloud_vpn_responder_aws_secret_key }}"
    security_token: "{{ cloud_vpn_responder_aws_security_token }} | default(omit)"
    region: "{{ cloud_vpn_responder_aws_region }}"
    filters:
      tag:Name: "{{ cloud_vpn_name }}-responder-vpc"
  register: out

- set_fact:
    cloud_vpn_responder_vpc_id: "{{ out['vpcs'][0]['vpc_id'] }}"

- ec2_vpc_route_table_facts:
    aws_access_key: "{{ cloud_vpn_responder_aws_access_key }}"
    aws_secret_key: "{{ cloud_vpn_responder_aws_secret_key }}"
    security_token: "{{ cloud_vpn_responder_aws_security_token }} | default(omit)"
    region: "{{ cloud_vpn_responder_aws_region }}"
    filters:
      vpc-id: "{{ cloud_vpn_responder_vpc_id }}"
  register: out

- set_fact:
    cloud_vpn_responder_route_table_id: "{{ out['route_tables'][0]['id'] }}"
