---
- add_host:
    name: initiator
    ansible_host: "{{ cloud_vpn_initiator_ip }}"
    ansible_user: "{{ cloud_vpn_initiator_user }}"
    ansible_connection: network_cli
    ansible_network_os: ios

- wait_for:
    port: 22
    search_regex: SSH

- pause:
    seconds: "{{ cloud_vpn_pause_before_config_seconds }}"

- ios_config:
    src: "ios/initiator/{{ peer_type_to_config[cloud_vpn_responder_type] }}/configure.j2"
  delegate_to: initiator
