---
- name: Add responder host
  add_host:
    name: responder
    ansible_host: "{{ cloud_vpn_responder_ip }}"
    ansible_user: "{{ cloud_vpn_responder_user }}"

- name: Wait for SSH port to be reachable
  wait_for:
    host: "{{ cloud_vpn_responder_ip }}"
    port: 22

- name: Pause for SSH daemon to settle and accept connections
  pause:
    seconds: "{{ cloud_vpn_pause_before_config_seconds }}"

- name: Install Libreswan package
  yum:
    name: libreswan
    update_cache: yes
  become: yes
  delegate_to: responder

- name: Start IPSEC service
  systemd:
    name: ipsec
    state: started
    enabled: yes
  become: yes
  delegate_to: responder

- name: Push Libreswan configuration file to responder
  template:
    src: rhel/responder/{{ peer_type_to_config[cloud_vpn_initiator_type] }}/configure_static.j2
    dest: /etc/ipsec.d/{{ cloud_vpn_name }}.conf
  become: yes
  delegate_to: responder

- name: Push Libreswan secrets file to initiator
  template:
    src: rhel/responder/{{ peer_type_to_config[cloud_vpn_initiator_type] }}/configure_psk.j2
    dest: /etc/ipsec.d/ipsec.secrets
  become: yes
  delegate_to: responder

- name: Restart IPSEC service
  systemd:
    name: ipsec
    state: restarted
  become: yes
  delegate_to: responder
