---
- cloudformation:
    aws_access_key: "{{ cloud_vpn_aws_access_key  }}"
    aws_secret_key: "{{ cloud_vpn_aws_secret_key  }}"
    region: "{{ cloud_vpn_aws_region }}"
    stack_name: "{{ cloud_vpn_name }}-responder-stack"
    template_body: "{{ lookup('template', 'templates/aws_instance/responder/provision.j2') }}"

- ec2_instance_facts:
    aws_access_key: "{{ cloud_vpn_aws_access_key }}"
    aws_secret_key: "{{ cloud_vpn_aws_secret_key }}"
    region: "{{ cloud_vpn_aws_region }}"
    filters:
      tag:Name: "{{ cloud_vpn_name }}-responder-instance"
      instance-state-name: running
  register: out

- set_fact:
    cloud_vpn_responder_ip: "{{ out['instances'][0]['public_ip_address'] }}"
